### PR TITLE
Add go.mod and go.sum for Go modules

### PR DESCRIPTION
**Pull request by flibustenet**
`go mod init github.com/go-ole/go-ole` and `go mod tidy`

### CODE REVIEW

**Comment by mattn** [comment]
Thanks. But I'm sorry. The files in example should not be included into go.mod. I just renamed example to _exmaple. And pushed go.mod and go.sum.

**Comment by mattn** [comment]
Ah, should be 1.12. Fixed.

**Comment by flibustenet** [comment]
You've put `module github.com/mattn/go-ole` ? you really want to change the import path ?

**Comment by mattn** [comment]
Fixed. Hmm, This repository was made with trasfering from mattn/go-ole. So something was wrong.

**Comment by flibustenet** [comment]
I think you can remove `require github.com/go-ole/go-ole v1.2.2`

**Pull request closed without merging**
