### PR TITLE
Support compilation on linux/ppc64le

### PR DESCRIPTION
**Pull request by adjackura**

### CODE REVIEW

**Comment by mattn** [comment]
for only compilation?

**Comment by adjackura** [comment]
Yeah, we had some build targets that referenced this and they fail when building for ppc64le, adding the stub seemed like the easiest fix

**Comment by adjackura** [comment]
To be a bit clearer, a cross platform tool that uses ole for windows specific bits will fail compilation for ppc64le as this library is listed as a global dependency in our build tooling.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
