### PR TITLE
IEnumVARIANT Test Case

### PR DESCRIPTION
**Pull request by jacobsantos**
Adds basic IEnumVariant test case.

### CODE REVIEW

**Comment by mattn** [comment]
I always surprised at your test or release management that was exactly.

**Comment by jacobsantos** [comment]
@mattn I am not sure what you mean.

My attempt was to get it to where you can determine whether a pull request was stable or damn near stable enough with whether the CI breaks. It is useful. I do tend to push before the code is ready just so that I can start testing. I find it is better and faster to just test locally.

I'm almost done with Destiny and should be done with Assassin's Creed. I think I have a better handle with the last few test cases that I will start doing that again. I just hope that more people write test cases in their pull requests, because you can never have too many good test cases.

Release management is, as you know, really just trying to keep master as stable as possible. I'm not sure if the point releases matter and I'm guessing no one is really using them. I believe your tool would allow for it, which is one reason I went with it. The other is that it is good practice for my other projects.

The test is supposed to really use the C# COM server, because you know that the functionality will always be available. Whereas, querying other Program IDs or GUIDs might not exist and therefore the tests will fail. I think I'm going to have to implement `_NewEnum` property in the C# project. It isn't hard. I was able to find some documentation during my research.

The problem was that I wasn't able to figure out if the tests were failing because WMI class ID doesn't exist or if the test case is incorrect.

**Comment by mattn** [comment]
> I am not sure what you mean.

Because you have doing things that I am not good, I always grateful to you. And always surprised to your accuracy works. :+1:

**Comment by jacobsantos** [comment]
@mattn Thanks man. I'm just experimenting with how to properly program. It is nice that you think what I'm doing is good. That means I'm getting better.

**Comment by jacobsantos** [comment]
I'm going to break changes out and do separate merge requests. Also needs to squash commits.

**Pull request closed without merging**
